sonar.projectKey=salimkhr_cours-iut-web
sonar.organization=salimkhr
sonar.sources=src
sonar.exclusions=src/cours/**,**/*.test.ts,**/*.spec.ts,**/*.test.tsx
sonar.typescript.tsconfigPath=tsconfig.json
