'use client'

import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import {MDXProvider} from "@mdx-js/react";
import {useMDXComponents} from "../../mdx-components";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <header>
          <NavBar/>
      </header>

      <MDXProvider components={useMDXComponents}>
          <div className=" mx-auto">
          {children}
      </div>
      </MDXProvider>
          <footer>
              <Footer/>
          </footer>
      </body>
    </html>
);
}
