/* eslint-disable @typescript-eslint/no-require-imports */
// Génère src/lib/skills/pedagogie.ts à partir de skills/pedagogie/
// Exécuté automatiquement via prebuild et predev.
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = process.cwd();
const SKILL_DIR = path.join(ROOT, 'skills', 'pedagogie');
const MANIFEST_FILE = path.join(SKILL_DIR, 'manifest.json');
const OUTPUT_FILE = path.join(ROOT, 'src', 'lib', 'skills', 'pedagogie.ts');

function hashContent(content) {
    return crypto.createHash('sha256').update(content).digest('hex').slice(0, 12);
}

function escapeTemplateLiteral(content) {
    return content.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

function readSkillFile(relativePath) {
    const fullPath = path.resolve(SKILL_DIR, relativePath);
    // Prévention de traversée de répertoire
    if (!fullPath.startsWith(SKILL_DIR + path.sep) && fullPath !== SKILL_DIR) {
        throw new Error(`Chemin interdit : ${relativePath}`);
    }
    if (!fs.existsSync(fullPath)) {
        throw new Error(`Fichier manquant : ${fullPath}`);
    }
    return fs.readFileSync(fullPath, 'utf-8').replace(/\r\n/g, '\n');
}

// Lecture du manifest
const manifest = JSON.parse(readSkillFile('manifest.json'));

// Chargement et hashage de tous les documents
const documents = {};
let combinedContent = '';

for (const doc of manifest.documents) {
    const content = readSkillFile(doc.path);
    const contentHash = hashContent(content);
    combinedContent += contentHash;
    documents[doc.id] = {
        id: doc.id,
        title: doc.title,
        uri: doc.uri,
        mimeType: 'text/markdown',
        content,
        contentHash,
        purpose: doc.purpose,
        load_when: doc.load_when,
    };
}

// Vérification d'intégrité : tous les chemins restent dans SKILL_DIR
for (const doc of manifest.documents) {
    const resolved = path.resolve(SKILL_DIR, doc.path);
    if (!resolved.startsWith(SKILL_DIR + path.sep)) {
        throw new Error(`Traversée de répertoire détectée pour le document "${doc.id}"`);
    }
}

// Mise à jour du manifest avec les hashes courants
const skillHash = hashContent(combinedContent);
const updatedManifest = {
    ...manifest,
    content_hash: skillHash,
    updated_at: new Date().toISOString(),
};
fs.writeFileSync(MANIFEST_FILE, JSON.stringify(updatedManifest, null, 2) + '\n');

// Génération du module TypeScript
const docEntries = Object.entries(documents).map(([id, doc]) => {
    return `    "${id}": {
        id: "${doc.id}",
        title: ${JSON.stringify(doc.title)},
        uri: ${JSON.stringify(doc.uri)},
        mimeType: "text/markdown" as const,
        content: \`${escapeTemplateLiteral(doc.content)}\`,
        contentHash: "${doc.contentHash}",
        purpose: ${JSON.stringify(doc.purpose)},
        load_when: ${JSON.stringify(doc.load_when)},
    }`;
}).join(',\n');

const tsContent = `// AUTO-GENERATED by scripts/generateSkillModule.js — ne pas éditer manuellement.
// Source canonique : skills/pedagogie/
// Régénérer avec : node scripts/generateSkillModule.js

export interface SkillDocument {
    id: string;
    title: string;
    uri: string;
    mimeType: "text/markdown";
    content: string;
    contentHash: string;
    purpose: string;
    load_when: string[];
}

export interface SkillManifestDoc {
    id: string;
    title: string;
    path: string;
    uri: string;
    purpose: string;
    load_when: string[];
}

export interface SkillManifest {
    id: string;
    name: string;
    version: string;
    description: string;
    entrypoint: string;
    supported_content_types: string[];
    roles: string[];
    documents: SkillManifestDoc[];
    updated_at: string;
    content_hash: string;
}

export const SKILL_MANIFEST: SkillManifest = ${JSON.stringify(updatedManifest, null, 2)};

export const SKILL_DOCUMENTS: Record<string, SkillDocument> = {
${docEntries}
};

export const SKILL_HASH: string = "${skillHash}";
export const SKILL_VERSION: string = "${manifest.version}";
`;

// Création du répertoire de sortie si nécessaire
const outputDir = path.dirname(OUTPUT_FILE);
if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
}

fs.writeFileSync(OUTPUT_FILE, tsContent);
console.log(`Skill module généré : src/lib/skills/pedagogie.ts (hash : ${skillHash})`);
console.log(`Documents embarqués : ${Object.keys(documents).join(', ')}`);
